sentry:
  dsn: '%env(SENTRY_DSN)%'
  options:
    attach_stacktrace: true
    capture_silenced_errors: false
    context_lines: 5
    default_integrations: true
    enable_compression: true
    environment: '%kernel.environment%'
    error_types: 'E_ALL & ~E_NOTICE'
    in_app_exclude:
      - '%kernel.cache_dir%'
      - '%kernel.project_dir%/vendor'
    in_app_include:
      - '%kernel.project_dir%'
    logger: 'php'
    max_breadcrumbs: 50
    max_value_length: 2048
    prefixes:
      - '/local_dir/'
    release: '{RELEASE_TAG}'
    sample_rate: 1
    send_attempts: 3
    send_default_pii: true

monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface

services:
  Monolog\Processor\PsrLogMessageProcessor:
    tags: { name: monolog.processor, handler: sentry }
