twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        js_data: '@App\Service\Data\JavaScript\JavaScriptDataManager'
        twig_data: '@App\Service\Data\Twig\TwigDataManager'
when@test:
    twig:
        strict_variables: true
