stages:
  - test

image: php:8.0

test:
  stage: test
  script:
    - make start
    - make doctrine-schema-update
    - make doctrine-schema-update-test
    - make doctrine-fixtures-load
    - make codeception-unit
    - make codeception-api

