version: '3'

services:
  db:
    build: ./docker/mysql
    container_name: ${PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    build: ./docker/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    links:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - /docker/storage/sessions
  webserver:
    build: ./docker/webserver
    container_name: ${PROJECT_NAME}_app
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ./:/var/www/html
    ports:
      - ${WEBSERVER_PORT}:80
  memcached:
    image: memcached:latest
    container_name: ${PROJECT_NAME}_memcached
    depends_on:
      - db
      - phpmyadmin
      - webserver
    ports:
      - ${MEMCACHED_PORT}:11211
