version: '3'

services:
  db:
    build: ./docker/mysql
    container_name: MPSync_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 4306:3306
  phpmyadmin:
    build: ./docker/phpmyadmin
    container_name: MPSync_phpmyadmin
    links:
      - db
    ports:
      - 8010:80
    volumes:
      - /docker/storage/sessions
  webserver:
    build: ./docker/webserver
    container_name: MPSync_app
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ./:/var/www/html
    ports:
      - 8009:80
  memcached:
    image: memcached:latest
    container_name: MPSync_memcached
    depends_on:
      - db
      - phpmyadmin
      - webserver
    ports:
      - '8011:11211'
