#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# api/config/routes.yaml
api_token:
  path: /api/authorization
  methods: ['POST']

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
